language: java
notifications:
  email:
    if: type = cron OR branch = master
    recipients:
      - cferiavi@redhat.com
      - jvilalop@redhat.com
      - pcattana@redhat.com
      - mbrophy@redhat.com
      - mrizzi@redhat.com
    on_success: change
    on_failure: always
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: project-xavier
    token:
      secure: $SONAR_TOKEN

env:
#  global:
#    - CAMEL_SPRINGBOOT_TRACING=false
#    - LOGGING_LEVEL_ROOT=info
#    - ANALYSIS_DATAINTEGRITY_LOG=false
  jobs:
    - TEST_PROFILE=unitTest MAVEN_PARAMS=
    - TEST_PROFILE=endToEnd MAVEN_PARAMS='-Dtest=Case1EndToEndIT'
    - TEST_PROFILE=endToEnd MAVEN_PARAMS='-Dtest=Case2EndToEndIT'

sudo: required

services:
  - docker

install:
  - cp ./configuration/settings.xml $HOME/.m2/settings.xml

script:
  - mvn test -P $TEST_PROFILE $MAVEN_PARAMS
#  - mvn test -Pcoverage
#  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi'
#  - bash <(curl -s https://codecov.io/bash)


